const $=s=>document.querySelector(s);
const state={season:"all",language:"all",query:""};
const favKey="m77-favorites", historyKey="m77-history";
const getStore=k=>JSON.parse(localStorage.getItem(k)||"[]");
const setStore=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const isFav=id=>getStore(favKey).includes(id);
const episodeById=id=>EPISODES.find(e=>e.id===id);
const fmtDate=d=>d?new Intl.DateTimeFormat(document.documentElement.lang==="en"?"en-US":"fa-IR",{year:"numeric",month:"long",day:"numeric"}).format(new Date(d+"T00:00:00")):"";
function card(e,compact=false){return `<a class="card ${compact?"small-card":""}" href="episode.html?id=${e.id}"><div class="poster"><img src="${e.poster}" alt="${e.title}" loading="lazy"><b>${String(e.episode).padStart(2,"0")}</b><button class="fav ${isFav(e.id)?"on":""}" data-fav="${e.id}" title="افزودن به علاقه‌مندی">★</button></div><div class="card-body"><small>فصل ${e.season} • قسمت ${e.episode}</small><h3>${e.title}</h3><span>${e.status==="upcoming"?"به‌زودی":"مشاهده جزئیات"} ←</span></div></a>`}
function bindFavs(){document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();let a=getStore(favKey),id=b.dataset.fav;a=a.includes(id)?a.filter(x=>x!==id):[...a,id];setStore(favKey,a);renderAll();});}
function filtered(){return EPISODES.filter(e=>{const season=state.season==="all"||String(e.season)===state.season;const lang=state.language==="all"||e.languages.includes(state.language);const q=state.query.trim().toLowerCase();const text=`${e.title} ${e.season} ${e.episode}`.toLowerCase();return season&&lang&&(!q||text.includes(q));});}
function renderEpisodes(){const list=filtered(),g=$("#episodeGrid");if(!g)return;g.innerHTML=list.map(card).join("");$("#emptyState").hidden=!!list.length;bindFavs();}
function renderLatest(){const g=$("#latestGrid");if(g)g.innerHTML=EPISODES.filter(e=>e.status==="released").sort((a,b)=>b.release.localeCompare(a.release)).slice(0,6).map(card).join("");bindFavs();}
function renderUpcoming(){const g=$("#upcomingGrid");if(!g)return;const list=EPISODES.filter(e=>e.status==="upcoming").sort((a,b)=>a.release.localeCompare(b.release));g.innerHTML=list.length?list.map(card).join(""):"<p class='empty'>فعلاً قسمت آینده‌ای ثبت نشده.</p>";bindFavs();}
function renderPersonal(){const fav=getStore(favKey).map(episodeById).filter(Boolean),his=getStore(historyKey).map(episodeById).filter(Boolean);const fg=$("#favoritesGrid"),hg=$("#historyGrid");if(fg)fg.innerHTML=fav.map(e=>card(e,true)).join("");if(hg)hg.innerHTML=his.map(e=>card(e,true)).join("");if($("#favoriteEmpty"))$("#favoriteEmpty").hidden=!!fav.length;if($("#historyEmpty"))$("#historyEmpty").hidden=!!his.length;bindFavs();}
function news(){const n=$("#newsList");if(n)n.innerHTML=NEWS.map((x,i)=>`<article class="news"><b>${String(i+1).padStart(2,"0")}</b><div><h3>${x.title}</h3><p>${x.text}</p></div></article>`).join("");}
function countdown(target){const el=$("#countdown");if(!el||!target)return;const tick=()=>{const diff=new Date(target+"T00:00:00").getTime()-Date.now();if(diff<=0){el.textContent="منتشر شد";return;}const d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;el.textContent=`${d} روز ${h} ساعت ${m} دقیقه ${s} ثانیه`;};tick();setInterval(tick,1000);}
function page(){const box=$("#episodePage");if(!box)return;const id=new URLSearchParams(location.search).get("id"),e=episodeById(id)||EPISODES[0];let h=`<a class="back" href="index.html#episodes">← بازگشت به قسمت‌ها</a><div class="episode"><div><div class="big-poster"><img src="${e.poster}" alt="${e.title}"></div><button class="btn dark full-fav" data-fav="${e.id}">${isFav(e.id)?"★ حذف از علاقه‌مندی":"☆ افزودن به علاقه‌مندی"}</button></div><div><small>فصل ${e.season} • قسمت ${e.episode}</small><h1>${e.title}</h1><p>${e.summary}</p><p class="meta">تاریخ انتشار: ${fmtDate(e.release)}</p>`;
if(e.status==="upcoming")h+=`<div class="count-box"><small>COUNTDOWN</small><h2 id="countdown">در حال محاسبه...</h2><button id="reminder" class="btn red">🔔 یادآوری</button></div>`;else h+=`<h2>پخش آنلاین</h2>${e.watch?`<a class="btn red" href="${e.watch}" target="_blank" rel="noopener">▶ پخش</a>`:`<span class="disabled">لینک پخش اضافه نشده</span>`}<h2>دانلود</h2>${Object.entries(e.downloads).map(([q,u])=>u?`<a class="btn dark" href="${u}" target="_blank" rel="noopener">⬇ ${q}p</a>`:`<span class="disabled">${q}p — لینک اضافه نشده</span>`).join("")}`;h+=`<div class="share-row"><button id="share" class="btn dark">↗ اشتراک‌گذاری</button></div></div></div>`;box.innerHTML=h;const fav=box.querySelector("[data-fav]");if(fav)fav.onclick=()=>{let a=getStore(favKey),x=fav.dataset.fav;a=a.includes(x)?a.filter(i=>i!==x):[...a,x];setStore(favKey,a);page();};if(e.status==="upcoming"){countdown(e.release);$("#reminder")?.addEventListener("click",()=>alert("یادآوری برای این قسمت در مرورگر شما ثبت شد."));}$("#share")?.addEventListener("click",async()=>{const url=location.href;if(navigator.share)await navigator.share({title:e.title,url});else{await navigator.clipboard?.writeText(url);alert("لینک قسمت کپی شد.");}});let his=getStore(historyKey).filter(x=>x!==e.id);setStore(historyKey,[e.id,...his].slice(0,10));}
function renderAll(){renderEpisodes();renderLatest();renderUpcoming();renderPersonal();}
renderAll();news();page();
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.season=b.dataset.season;renderEpisodes();});
$("#search")?.addEventListener("input",e=>{state.query=e.target.value;renderEpisodes();});
$("#languageFilter")?.addEventListener("change",e=>{state.language=e.target.value;renderEpisodes();});
document.querySelector(".menu")?.addEventListener("click",()=>document.querySelector("nav")?.classList.toggle("open"));
$("#langBtn")?.addEventListener("click",()=>{document.documentElement.lang=document.documentElement.lang==="fa"?"en":"fa";document.documentElement.dir=document.documentElement.lang==="en"?"ltr":"rtl";$("#langBtn").textContent=document.documentElement.lang==="en"?"FA":"EN";});
