const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const themeKey='m77-theme', historyKey='m77-history', favKey='m77-favs';
const state={season:new URLSearchParams(location.search).get('season')||'all',query:'',filter:'all'};
const store=k=>JSON.parse(localStorage.getItem(k)||'[]'); const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const episodeById=id=>EPISODES.find(e=>e.id===id); const fav=id=>store(favKey).includes(id);
function poster(e){const src=`images/episodes/${e.id}.jpg`;return `<img src="${src}" alt="${e.title}" loading="lazy" onerror="this.onerror=null;this.src='assets/placeholder.svg'" >`}
function card(e){return `<a class="episode-card" href="episode.html?id=${encodeURIComponent(e.id)}"><div class="poster">${poster(e)}<div class="poster-placeholder" ${e.poster?'style="display:none"':''}>تصویر قسمت</div>${e.status==='upcoming'?'<span class="badge upcoming">بعدی</span>':'<span class="badge">جدید</span>'}</div><div class="card-info"><small>فصل ${e.season} · قسمت ${e.episode}</small><h3>${e.title}</h3><p>${e.languages.includes('sub')?'زیرنویس فارسی':'اطلاعات قسمت'}</p></div></a>`}
function renderLatest(){const box=$('#latestGrid');if(!box)return;let list=EPISODES.filter(e=>e.season===6&&e.status==='released').sort((a,b)=>b.episode-a.episode);box.innerHTML=list.map(card).join('')}
function renderUpcoming(){const box=$('#upcomingBanner');if(!box)return;const e=EPISODES.find(x=>x.season===6&&x.status==='upcoming');if(!e){box.innerHTML='';return}box.innerHTML=`<article class="release-banner"><div class="release-art">${poster(e)}<div class="poster-placeholder" ${e.poster?'style="display:none"':''}>تصویر قسمت آینده</div></div><div class="release-copy"><span class="release-kicker">قسمت بعدی · فصل ${e.season}</span><h2>${e.title}</h2><div class="release-meta"><span>فصل ${e.season}</span><span>قسمت ${e.episode}</span></div><p>تاریخ پخش احتمالی</p><strong class="release-date-fa">۲۹ آبان</strong><a class="primary-btn" href="episode.html?id=${encodeURIComponent(e.id)}">جزئیات قسمت ←</a></div></article>`}
function renderNews(){const box=$('#newsList');if(!box)return;box.innerHTML=NEWS.map((n,i)=>`<article class="news-item"><span class="news-no">${String(i+1).padStart(2,'0')}</span><div><h3>${n.title}</h3><p>${n.text}</p></div></article>`).join('')}
function renderFeatured(){const box=$('#featuredGrid');if(!box)return;const list=EPISODES.filter(e=>e.status==='released').sort((a,b)=>b.release.localeCompare(a.release)).slice(0,4);box.innerHTML=list.map(card).join('');$('#hideFeatured')?.addEventListener('click',()=>document.querySelector('.featured-block')?.classList.toggle('featured-hidden'))}
function renderArchive(){const box=$('#episodeGrid');if(!box)return;let list=EPISODES.filter(e=>state.season==='all'||String(e.season)===String(state.season));if(state.query){const q=state.query.toLowerCase();list=list.filter(e=>`${e.title} ${e.episode} ${e.season}`.toLowerCase().includes(q))}if(state.filter==='sub')list=list.filter(e=>e.languages.includes('sub'));if(state.filter==='new')list=list.filter(e=>e.status==='released'&&e.season===6);list.sort((a,b)=>{if(a.season===b.season)return b.episode-a.episode;return String(b.season).localeCompare(String(a.season),undefined,{numeric:true})});box.innerHTML=list.map(card).join('');$('#emptyState').hidden=list.length>0}
function setupTheme(){const root=document.documentElement;const saved=localStorage.getItem(themeKey)||'light';root.dataset.theme=saved;const b=$('#themeBtn');if(b)b.textContent=saved==='dark'?'☀':'☾';b?.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;localStorage.setItem(themeKey,next);b.textContent=next==='dark'?'☀':'☾';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',next==='dark'?'#0f1014':'#ffffff')})}
function setupNav(){const menu=$('#menuBtn'),nav=$('#mainNav');menu?.addEventListener('click',()=>nav?.classList.toggle('open'));$$('.main-nav a').forEach(a=>a.addEventListener('click',()=>nav?.classList.remove('open')))}
function setupSearch(){const p=$('#searchPanel');$('#searchBtn')?.addEventListener('click',()=>{p?.classList.toggle('open');$('#globalSearch')?.focus()});$('#closeSearch')?.addEventListener('click',()=>p?.classList.remove('open'));$('#globalSearch')?.addEventListener('input',e=>{state.query=e.target.value;if($('#search'))$('#search').value=e.target.value;if($('#episodeGrid'))renderArchive()}) ;$('#search')?.addEventListener('input',e=>{state.query=e.target.value;renderArchive()})}
function setupArchive(){if(!$('#seasonTabs'))return;$$('#seasonTabs button').forEach(b=>b.addEventListener('click',()=>{$$('#seasonTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.season=b.dataset.season;renderArchive()}));$$('.filter-chips button').forEach(b=>b.addEventListener('click',()=>{$$('.filter-chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderArchive()}));const current=state.season;const active=$(`#seasonTabs button[data-season="${current}"]`);if(active){$$('#seasonTabs button').forEach(x=>x.classList.remove('active'));active.classList.add('active')}}
function setupMisc(){$('#closeAnnounce')?.addEventListener('click',()=>document.querySelector('.announce')?.remove());$('#langBtn')?.addEventListener('click',()=>{const root=document.documentElement;const en=root.lang==='en';root.lang=en?'fa':'en';root.dir=en?'rtl':'ltr';$('#langBtn').textContent=en?'EN':'FA'})}
function episodePage(){const box=$('#episodePage');if(!box)return;const id=new URLSearchParams(location.search).get('id'),e=episodeById(id)||EPISODES[0];const watch=e.watch?`<a class="detail-btn primary" href="${e.watch}" target="_blank" rel="noopener">▶ پخش آنلاین</a>`:`<span class="detail-btn disabled">پخش آنلاین در دسترس نیست</span>`;box.innerHTML=`<a class="back" href="episodes.html">→ بازگشت به آرشیو</a><div class="episode-detail"><div class="detail-poster">${poster(e)}<div class="poster-placeholder" ${e.poster?'style="display:none"':''}>تصویر قسمت</div></div><div class="detail-copy"><span class="eyebrow">SEASON ${e.season} · EPISODE ${e.episode}</span><h1>${e.title}</h1><p>${e.summary}</p><div class="detail-meta"><span>فصل ${e.season}</span><span>قسمت ${e.episode}</span></div>${e.status==='upcoming'?`<div class="count-box"><span>تاریخ پخش احتمالی</span><strong>۲۹ آبان</strong></div>`:`<div class="detail-actions">${watch}</div>`}</div></div>`}
setupTheme();setupNav();setupSearch();setupArchive();setupMisc();renderLatest();renderUpcoming();renderNews();renderFeatured();renderArchive();episodePage();
